---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  clusterIP: None  # This makes it headless - remove the type field
  selector:
    app: app-database
  ports:
  - port: 3306
    targetPort: 3306
